#!/bin/bash
 
# Hal9000
# Maintainer: Nicolas
# Authors: nicolas.dywicki@gmail.com
# chkconfig: - 80 05
 
### BEGIN INIT INFO
# Provides:          hal9000 node application
# Required-Start:    $syslog $remote_fs
# Required-Stop:     $syslog $remote_fs
# Should-Start:      $local_fs
# Should-Stop:       $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Script for Hal9000 Node Application
# Description:       Script for Hal9000 Node Application
### END INIT INFO
 
# An application name to display in echo text.
# An application name to display in echo text.
# NAME="My Application"
# The full path to the directory containing the node and forever binaries.
# NODE_BIN_DIR=/home/node/local/node/bin
# Set the NODE_PATH to the Node.js main node_modules directory.
# NODE_PATH=/home/node/local/node/lib/node_modules
# The directory containing the application start Javascript file.
# APPLICATION_DIRECTORY=/home/node/my-application
# The application start Javascript filename.
# APPLICATION_START=start-my-application.js
# Process ID file path.
# PIDFILE=/var/run/my-application.pid
# Log file path.
# LOGFILE=/var/log/my-application.log
 
NAME="hal9000"
NODE_BIN_DIR=/usr/bin
NODE_PATH=/usr/local/lib/node_modules/
APPLICATION_DIRECTORY=/opt/hal9000
APPLICATION_START=server.js
PIDFILE=/var/run/$NAME/$NAME.pid
LOGFILE=/var/log/$NAME/$NAME.log
FOREVER_DIRECTORY=/home/pi/.forever

PATH=$NODE_BIN_DIR:$PATH
export NODE_PATH=$NODE_PATH

export NODE_ENV=production
 
start() {
        echo "Starting $NAME"
	cd ~/
        /usr/local/bin/forever --pidFile $PIDFILE \
                -a -l $LOGFILE --minUptime 5000 --spinSleepTime 2000 --sourceDir $APPLICATION_DIRECTORY \
                start $APPLICATION_START &
        RETVAL=$?
}
 
stop() {
        if [ -f $PIDFILE ]; then
                echo "Shutting down $NAME"
                #rm -f $PIDFILE
		        cd ~/
		        /usr/local/bin/forever stop $APPLICATION_DIRECTORY/$APPLICATION_START
                RETVAL=$?
        else
                echo "$NAME is not running."
                RETVAL=0
        fi
}
 
restart() {
        echo "Restarting $NAME"
        stop
        start
}
 
status() {
        echo "Status for $NAME:"
        /usr/local/bin/forever list
        RETVAL=$?
}
 
case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        status)
                status
                ;;
        restart)
                restart
                ;;
        *)
                echo "Usage: {start|stop|status|restart}"
                exit 1
                ;;
esac
exit $RETVAL
